<?php
/**
 * Author: Hieu Nguyen
 * Date: 2/11/2022
 * File: grad_student.class.php
 * Description: create grad_student class
 *
 */

class GradStudent extends Student
{
    private $program;

    //static data member to count the number of students
    private static $student_count = 0;

    //constructor
    public function __construct($name, $gender, $major, $gpa, $program)
    {
        parent::__construct($name, $gender, $major, $gpa);
        $this->program = $program;
        self::$student_count++; //when a new object is created, student_count +1, start at 0
    }

    //create getter for program to get student's program
    public function getProgram()
    {
        return $this->program;
    }

    //create setter for program
    public function setProgram($program)
    {
        $this->program = $program;
    }

    //retrieve the number of students
    public static function getStudentCount(): int
    {
        return self::$student_count;
    }

    public function toString()
    {
        parent::toString(); // TODO: Change the autogenerated stub
        echo "Program: ", $this->getProgram();
    }


}